puts "🌱 Seeding spices..."

# Seed your database here
require_all 'app/models'
o2 =Owner.create(name: "Hieu Nguyen and Yaneizy Castillo", occasion:"Graduating from Flatiron School", location:"New York")

s1 =Store.create(name:"The Flower Shop", owner_id: o2.id)



Flower.create(name: "Peonies", season:"Late spring through early summer", color:"Pink, red, orange, yellow, and white", price: 10, quantity: 10, image_url: "https://images.squarespace-cdn.com/content/v1/56e1cc7c8259b5ca8c33d158/1590850442700-HX62FNKIEIHA5D18YI3L/Peonies.jpeg?format=1000w", description: "From white to red, coral, purple, pink, and yellow, peonies can come in a variety of colors! The key to growing a thriving peony is to make sure you plant at the proper time, plant correctly, and of course, care for it all throughout the year, even when they aren’t necessarily in season. Since peonies can grow rather tall (sometimes even as tall as five feet!), you’ll need to make sure that the spot you choose is spacious enough. And remember, peonies can come back year after year, so you’ll need to think long term.", store_id: s1.id)


Flower.create(name: "Aster", season:"Late-summer and early-fall", color:"Purple", price: 5, quantity: 15,image_url: "https://www.gardeningknowhow.com/wp-content/uploads/2021/01/alpine-asters.jpg", description: "Most of these beautiful perennials are native to Eurasia, with only two from North America — the New York and New England asters. Their one-inch flowers are starbursts of closely packed, narrow petals in intense blue, purple, lilac, pink, or white. They brighten a garden in late summer through fall and are great for attracting butterflies, bees, and other pollinators. The word “aster” means star in Greek, and it sparkles as the September birthday flower and also for a 20th wedding anniversary.", store_id: s1.id)


Flower.create(name: "Carnations", season:"Late spring, usually May", color:"Yellow, white, red, pink, and scarlet", price: 12, quantity: 20,image_url: "https://www.directgardening.com/1236-large_default/perennial-carnations.jpg", description: "These come in 3 different types: large flowered carnations, spray carnations, and dwarf flowered carnations. Large flowered carnations can grow to over 20 inches high with one large bloom per stem. These are also referred to as the florist’s carnation. Spray and dwarf carnations have smaller blooms but have multiple blooms per stem. These carnations grow to 12 inches and are more commonly found in gardens. When planting carnations take care to plant in a well-draining soil and in an area with ample sunlight. Carnations can have different meanings depending on their color – a pink carnation symbolizes motherly love, a white carnation means good luck, a yellow carnation means disappointment, etc. Their versatility has made them an extremely popular flower for all occasions.", store_id: s1.id)


Flower.create(name: "Dahlias", season:"Mid-summer through fall", color:"Peach, red, lavender, white, yellow, orange, pink, and bi-color", price: 9, quantity: 12, image_url: "https://www.whiteflowerfarm.com/mas_assets/cache/image/5/e/5/6/24150.Jpg", description: "These bold blooms come in a wide range of color and can be easily incorporated into any existing or new garden. And unlike most plants, these flowers thrive in some shade. They also flower extremely long, first blooming midsummer and lasting through the first frost. However, even though Dahlias are perennials, they are tuberous rooted plants so they should be replanted every spring after resting.", store_id: s1.id)


Flower.create(name: "Chrysanthemum", season:"Late summer, fall, and early winter when days are shorter", color:"Shades of white, yellow, orange, lavender, purple, and red", price: 6, quantity: 11,image_url: "https://www.gardendesign.com/pictures/images/675x529Max/site_3/paradiso-pink-mum-fall-flower-proven-winners_14469.jpg", description: "Cultivated mums originated in China more than 3,000 years ago, and have become familiar and well-loved fall flowers the world over. Thousands of varieties with unique flower shapes brighten home gardens, containers, median strips, and parking lots from late summer through frost with their orange, red, yellow, purple, or white blooms. Chrysanthemums are perennials and will come back year after year if planted early in the season so that they become established and can overwinter. In addition to their beauty, chrysanthemum flowers can be made into a tea, and the leaves can be eaten as salad greens.", store_id: s1.id)


Flower.create(name: "Lilies", season:"Early summer to fall", color:"Yellow, white, pink, red, and orange", price: 8, quantity: 8,image_url: "https://harvesting-history.com/wp-content/uploads/2020/04/HH_Asiatic-Lilies_Woo-Images_Forever-Susan_3.26.2021.jpg", description: "are one of the most popular and versatile flowers in the world. Coming in a variety of colors and known for their strong fragrance, this elegant bloom is a show-stopper on its own while also serving as the perfect complement to any bouquet. In fact, lilies are one of the most popular flowers in the world, and it’s not hard to see why. There are over 100 different types of true lilies belonging to the “lilium” genus. Lilies are found dominantly in the Northern Hemisphere of the world.", store_id: s1.id)


Flower.create(name: "Marigold", season:"All summer and into fall", color:"Orange and Yellow", price: 7, quantity: 8, image_url: "https://www.gardendesign.com/pictures/images/900x705Max/dream-team-s-portland-garden_6/marigold-flowers-orange-pixabay_12708.jpg", description: "Beautifully orange and gold in color, marigolds are known to symbolize a desire for wealth and success. They are such a bright color that their pigments are also used in the textile and food industry! Marigolds are a versatile flower – they may also be used when grieving over the loss of a loved one or when celebrating those who have passed.", store_id: s1.id)

Flower.create(name: "Alstroemeria", season:"Summer", color:"Shades of red, orange, purple, green, white, flecked and striped", price: 7, quantity: 8, image_url: "https://www.gardenia.net/storage/app/public/plant_family/detail/18488792_mOptimized.jpg", description: "These are more often called either Peruvian Lilies or Lilies of the Incas and are native to South America. Peruvian Lilies come in a variety of warm colors like pink and orange and are symbolic of friendship, wealth and devotion. These flowers bloom in late spring/early summer when exposed to direct sunlight and watered weekly (water more often when you notice soil looking dry, water less when the soil looks soggy).", store_id: s1.id)


Flower.create(name: "Black-Eyed Susan", season:"March to May", color:"Bright yellow", price: 7, quantity: 8, image_url: "https://jmoreliving.com/wp-content/uploads/2018/03/blackeyedsusan.jpg", description: "Cheerful black-eyed Susans are one of North America’s favorite perennial wildflowers that are frequently seen in fields and meadows. They are a popular addition to a sunny garden since they are hardy, they can tolerate drought and a variety of soils, and they can reseed and come back year after year. Black-eyed Susans are perfect for a beginner gardener. Their jolly orange petals and brown centers represent encouragement and can be given to a friend who could use a bouquet of optimism.", store_id: s1.id)


Flower.create(name: "California Poppy", season:"Late winter to early spring", color:"Pale yellow, orange, or cream in the wild,", price: 7, quantity: 8, image_url: "https://www.selectseeds.com/product/image/SS/12003/california_poppy_pink_champagne_seeds.jpg", description: "Also known as the golden poppy, this bright red, orange, or yellow native plant is the state flower of California. It is either an annual or a perennial depending on the climate — annual in colder areas and perennial in warmer regions. The California poppy is a sun worshipper that opens its petals in the sun and closes them on cloudy days and at night. Native Americans used preparations of the plant to relieve anxiety and for various kinds of pain, but unlike its cousin the opium poppy, it does not contain any opiates.", store_id: s1.id)

# 10


Flower.create(name: "Azalea", season:"Late March to mid-May", color:"Shades of yellow, pink, orange, red and white", price: 7, quantity: 8, image_url: "https://shop-static.arborday.org/media/0002350_orange-azaleas-mollis-hybrid.jpg", description: "One of the hallmarks of late spring are the vivid azaleas that bloom in yards, along trails, and in woodlands. These familiar shrubs are either evergreen or deciduous and display a profusion of white, pink, red, orange, yellow, or purple flowers that cover the bushes. Azaleas prefer shady locations under trees and thrive in acidic soil. But be careful — all parts of the azalea are poisonous.", store_id: s1.id)


Flower.create(name: "Crocus", season:"Late winter to early spring", color:"White, yellow, orange, and purple", price: 7, quantity: 8, image_url: "https://h2.commercev3.net/cdn.gurneys.com/images/800/87999.jpg", description: "For many of us, the first hint of spring is the little crocus pushing up through the snow. Ninety species of these beautiful bulbs are native to North Africa and the Mediterranean, all the way east to China. Their cup-shaped flowers come in an array of lavender, purple, white, yellow, and multicolored depending on the species and variety. Crocuses are not only grown for their cheerful blooms, but also for the stigmas of autumn-blooming crocuses that are harvested in Iran for the highly prized saffron spice.", store_id: s1.id)


Flower.create(name: "Daisies", season:"Late spring", color:"Purple, white, pink, red, and blue", price: 7, quantity: 8, image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gerber-daisy-types-1586981130.jpg", description: "Daisies are found on every continent other than Antarctica and belong to one of the largest known plant families. Daisies symbolized innocence, a connotation that comes from the Victorian era. Based on what color the daisy is, the flower can take on another meaning. Daisy flowers prefer full sun and average soil conditions. Depending on the variation, they can grow to anywhere between 8 inches to 4 feet. Care tip: only water during the summer only if rainfall is less than 1 inch per week.", store_id: s1.id)


Flower.create(name: "Daffodil", season:"Late winter and early spring", color:"Yellow and white", price: 7, quantity: 8, image_url: "https://mobileimages.lowes.com/productimages/f3c85dfb-cb30-4c06-878b-e245bd197ad4/11369044.jpg?size=pdhi", description: "Daffodils go by many names depending on the species and variety — narcissus, jonquils, or paperwhites — but they are all daffodils and they all belong to the genus Narcissus. These jaunty flowers are perennial bulbs that will multiply every year in the garden as long as they have good soil with adequate drainage. They are deer resistant and possess a natural pesticide so that few insects bother them except for pollination. Daffodils are the national flower of Wales and the 10th-anniversary posy.", store_id: s1.id)


Flower.create(name: "Delphinium", season:"Early summer and late summer/early fall ", color:"Blue, purple, lavender, pink, scarlet, white, and rarely yellow", price: 7, quantity: 8, image_url: "https://www.ftd.com/blog/wp-content/uploads/2016/10/hero-delphinium-meaning-720x500.jpg", description: "The delphinium, which is often called larkspur, is an herbaceous perennial with tall spikes of blue or purple flowers. It is indispensable in English cottage gardens and frequently used in florists’ bouquets for its height and vivid blues and purples, with cultivars in whites, reds, and even yellows. It is said that West Coast Native Americans used the flowers to make blue and purple dyes. Delphiniums are a beautiful accent in the garden, but don’t let them escape to a grazing meadow — they’re highly toxic to humans and animals.", store_id: s1.id)


Flower.create(name: "Dusty Miller", season:"Midsummer", color:"Soft, warm, cloudy gray with a slate undertone", price: 7, quantity: 8, image_url: "https://www.gardeningknowhow.com/wp-content/uploads/2021/07/marine-cineraria.jpg", description: "Dusty miller is a half-hardy perennial valued for its lacy, wooly, silvery-gray foliage. It is usually grown as a bedding plant or in containers where it acts as a light-colored accent against darker plants. It is especially beautiful paired with pink, reddish-purple, or violet flowers. Dusty millers grow best in full sun and can stand heat and drought like in its native Mediterranean habitat. ", store_id: s1.id)


Flower.create(name: "Gardenias", season:"May through July", color:"Red, pink, pale yellow", price: 7, quantity: 8, image_url: "https://i.pinimg.com/originals/89/b4/a8/89b4a887e944c79385523acbee586c56.jpg", description: "Gardenia’s are most famous for their scented and waxy white flowers that can bring a garden to life. Depending on your geographical location (and personal preference) you get to decide whether your gardenia will live indoors or outdoors. To ensure that your gardenias bloom throughout their growing season, keep the soil well drained and at a pH of 4.5 to 5.5 regardless of whether they are planted in a pot or outside in the garden. These plants also need ample amounts of water, so make sure to never let your gardenia dry out – water regularly.", store_id: s1.id)


Flower.create(name: "Iris", season:"Spring or summer", color:"Blue-violet", price: 7, quantity: 8, image_url: "https://cdn11.bigcommerce.com/s-ih8o56kgor/images/stencil/1280x1280/products/4525/7247/siberian-iris-iris-sibirica__00262.1564590282.jpg?c=2", description: "Elegant irises are native to Europe, the Middle East, northern Africa, Asia, and North America. They grow from either perennial rhizomes or bulbs, and range in size from 8” to 36” high, with flat, sword-shaped or curved leaves, and purple, yellow, orange, blue, or white flowers, depending on the species and variety. The rhizomes of some iris species are called orrisroot and are used in perfumery and for potpourris. They are the state flower of Tennessee, the 25th wedding anniversary flower, and the national symbol of France from the fleur-de-lis, a graphic representation of the iris.", store_id: s1.id)


Flower.create(name: "Orchids", season:"Summer", color:"Green, red, pink, white, purple, yellow, orange, and blue", price: 7, quantity: 8, image_url: "https://leggypeggy.files.wordpress.com/2015/04/yellow-green-orchid.jpg", description: "Did you know that orchids are one of the oldest flower plants known to man? Scientists have speculated that orchids have been around as far back as 100 million years. With over 30,000 types of orchids some of the most popular types include Phalaenopsis Orchid, Dendrobium Orchid, Cattleya Orchid and Vanilla Orchid. Orchids generally represent love, fertility, thoughtfulness and charm. However, each variety of these flower types has it’s own color has its own meaning. Phalaenopsis orchids symbolize health and prosperity, while Dendrobium orchids represent wisdom & beauty. Cymbidium orchids symbolize strength & nobility, and Oncydium orchids symbolize love & talent.", store_id: s1.id)


Flower.create(name: "Periwinkle", season:"Spring and fall", color:"Purple", price: 7, quantity: 8, image_url: "https://cdn.shopify.com/s/files/1/0059/8835/2052/products/Vinka_Minor_Periwinkle_5_650x.jpg?v=1612444305", description: "Periwinkle, also known as myrtle, is a popular ground cover with shiny dark green leaves that bloom in April and May with purple, blue, or white flowers. There are over 30 varieties of the small plant that include variegated leaf types and lavender, blue, burgundy, or white flowers. They are great for erosion control, tumbling over rock walls in the sun, or spreading out underneath trees in the shade. Periwinkle is the flower of sweet and sad remembrance, and has often been planting over graves.", store_id: s1.id)

# 20
Flower.create(name: "Petunia", season:"Summer", color:"Pink, purple, red, and white", price: 7, quantity: 8, image_url: "https://www.indiaplants.com/photos/Plants/P/img1459_33573547.jpg", description: "The cheerful petunia, a staple of old-fashioned gardens, planters, and hanging pots, is more vivid than ever with red, yellow, pink, purple, lavender, white, multicolored, or striped blossoms. They are reliable flowers that will bloom from spring through autumn if grown in the sun and deadheaded consistently. Many of them feel sticky to the touch due to sap that is exuded from the plant tissues to protect them from insect pests. Petunias are native to South America and are related to tomatoes, peppers, eggplants, and tobacco.", store_id: s1.id)

Flower.create(name: "Ranunculus", season:"Early spring until the beginning of summer", color:"White, pink, orange, red, yellow, purple, and cream in various shades", price: 7, quantity: 8, image_url: "https://images.tulipworld.com/mmTW/Images/450X450/3374.jpg", description: "Ranunculus flowers are varieties of the big, showy, Persian buttercups that grow from claw-shaped corms and come in a variety of bright colors. Their layers of paper-thin, glossy petals give the blossoms a rose-like appearance that is appealing for wedding bouquets or  long-lasting cut flowers. Ranunculus are not commonly grown in home gardens, but they could be. Southern gardeners can plant the corms in the fall for spring blooms, and northern gardeners can plant in the early spring for summer blossoms.", store_id: s1.id)

Flower.create(name: "Roses", season:"Midspring to fall", color:"Red, yellow, pink, purple, orange, and white", price: 7, quantity: 8, image_url: "https://www.sallyhelmy.com/wp-content/uploads/2018/10/header-2.jpg", description: "Like the flower itself, the history of the rose is very colorful. Roses have been naturally growing for over 35 million years! However, they were not known to be cultivated until about 5,000 years ago. Their usage began not just as a decorative touch to one’s home, but they were also used for medicinal purposes, to make perfumes, and their petals were even used as confetti for festive occasions. Getting your roses into water quickly is the first step in caring for them. Fill a vase ¾ full of fresh, cool tap water. The roses will absorb the water, soaking up the nutrients that will travel up to the bloom and create a lively flower. Check the water level in your rose’s vase every day and add more water as needed. Shop these classic flowers for Valentine’s Day!", store_id: s1.id)

Flower.create(name: "Snapdragon", season:"Spring and fall", color:"Pink, orange, yellow, peach, purple, white, red and bicolor.", price: 7, quantity: 8, image_url: "https://h2.commercev3.net/cdn.gurneys.com/images/800/69576.jpg", description: "Snapdragon flowers, shaped like little dragon snouts, are native to the United States, North Africa, and Europe, and have been widespread posies for centuries. Their flowers bloom from the bottom to the top of tall stalks in the summer and fall and come in yellow, peach, pink, orange, purple, red, white, and bicolor. Snapdragons are picky about their pollinators! Large bumblebees are the only insects that are strong enough to open the upper and lower lips of the snapdragon flower to crawl inside to drink the nectar and inadvertently cover themselves in pollen.", store_id: s1.id)

Flower.create(name: "Sunflowers", season:"Summer into autumn", color:"Yellow", price: 7, quantity: 8, image_url: "https://m.media-amazon.com/images/I/81MR7K2D+XS._AC_SX466_.jpg", description: "Sunflowers are one of the most popular flower types and are best known for their dazzling yellow color and large size. Sunflowers generally symbolize adoration, loyalty and longevity in the language of flowers. Native Americans view sunflowers as a symbol of harvest and bounty since the flower provides seeds and pigments on top of being visually beautiful. Sunflowers need direct sunlight for 6 to 8 hours per day and require hot conditions to flower well. Sunflowers also have long roots that require plenty of room to spread out, so soil should be well dug and not too dense for growth. Avoid over fertilization or risk your stems breaking in the fall.", store_id: s1.id)

Flower.create(name: "Tulips", season:"Spring", color:"Purple, pink, red, orange, and yellow", price: 7, quantity: 8, image_url: "https://www.gardeningknowhow.com/wp-content/uploads/2008/07/tulips.jpg", description: "There are over 150 species of tulips with over 3,000 different varieties and are part of the lily family. Like most common flowers, tulips come in a large variety of colors that each have their own meaning. As a signal of the arrival of spring, these blooms are often associated with the Easter holiday. Tulips were at one point more valuable than gold in Holland during a period of “Tulip Mania” and their popularity has only spread with time! Tulip bulbs should be planted in the fall in areas where they can receive partial to full sun. Tulips will fare better in soil that allows for drainage since over watering will drown the bulb and roots.", store_id: s1.id)


Flower.create(name: "Violet", season:"Late winter and early spring", color:"Purple/violet", price: 7, quantity: 8, image_url: "https://www.bluestoneperennials.com/img/PHVP/650/PHVP-0-Phlox-subulata-Violet-Pinwheels-wg.1574190019.jpg", description: "There are over 500 species of these merry little wildflowers mostly in the temperate northern hemisphere, popping up in lawns, woodlands, streambanks, and hillsides. True violets are annual, perennial, or even small shrubs with white, yellow, lavender, or purple flowers. Our garden pansies are also violets but are larger, multicolored cultivars of the European flower known as heartsease. The violet is February’s birth flower, and the state flower of Illinois, New Jersey, and Wisconsin.", store_id: s1.id)

Flower.create(name: "Zinnia", season:"Late spring until the first frost in fall", color:"Pink, purple, yellow, orange, lavender, white, red, and green", price: 7, quantity: 8, image_url: "https://www.gardendesign.com/pictures/images/900x705Max/dream-team-s-portland-garden_6/zinnia-flowers-mixed-flowers-shutterstock-com_12811.jpg", description: "Colorful, easy-to-grow zinnias are a beginner gardener’s dream. They can be seeded from the last frost to early summer and will consistently produce blooms all season if dying blooms are deadheaded — truly a “cut and come again” flower. They are herbaceous annuals, native to Mexico, South America, and the southwestern U.S. that are of varying heights, with bright 1” to 7” diameter flowers that are single, semi-double, or double. Zinnias are perfect for a butterfly garden, with their red, pink, purple, yellow, white, or orange blossoms that attract pollinators of all kinds including hummingbirds.", store_id: s1.id)

Flower.create(name: "Ageratum", season:"Late spring through fall", color:"Blue, purple, white, and pink", price: 7, quantity: 8, image_url: "https://www.gardendesign.com/pictures/images/900x850Max/site_3/blue-mink-floss-flower-ageratum-houstonianum-shutterstock-com_13700.jpg", description: "Ageratums are also known as the floss flower. These plants produce flowers that are fluffy and last for an extended period of time.Most types are mounding plants six to ten inches tall and wide, but there are taller types.The common garden ageratum (A. houstonianum), also known as floss flower and blue mink, is frequently cultivated as an ornamental annual. Several dwarf varieties are commonly used as edging plants.", store_id: s1.id)

Flower.create(name: "Candytuft", season:"Early spring through early/mid-summer;", color:"Purple, white, pink, red, and yellow", price: 7, quantity: 8, image_url: "https://www.applewoodseed.com/wp-content/uploads/2016/11/IUMB.602.jpg", description: "The Candytuft plant is also known as iberis. These small plants are generally less than a foot tall and are classified as hardy annuals. The flowers have a sweet smell and come in colors such as white, pink and purple. The plants do well even in poor soils and self-seed readily, so you might find yourself with plants springing up every year.", store_id: s1.id)

#30

puts "✅ Done seeding!"
